# -*- coding: utf-8 -*-
"""pValue_10_20_select.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdG1BiwyB5_bU3SvbjHLuwSQCMhDAYTm
"""

import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ttest_ind

from scipy import stats

data = pd.read_csv("/content/drive/MyDrive/omicData/p_value_10_20_select/omics1_3_Value_poor.csv")
data

gene_normal = data[data['p-value'] < 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001]
gene_normal

gene_normal.to_csv("/content/drive/MyDrive/omicData/p_value_10_20_select/omics1_3_poor_pValue.csv",index=False)







